package oci

import (
	"context"

	"github.com/oracle/oci-go-sdk/common"
	"github.com/oracle/oci-go-sdk/resourcemanager"
)

const (
	tf_version string = "1.2.x"
)

type Stack struct {
	Name             string
	Client           resourcemanager.ResourceManagerClient
	CompartmentID    string
	Zipfile          string
	TerraformVersion string
}

// DeleteStack deletes a stack - Generated by Copilot
func (s *Stack) DeleteStack(stackID string) error {
	req := resourcemanager.DeleteStackRequest{
		StackId: &stackID,
	}
	_, err := s.Client.DeleteStack(context.Background(), req)
	if err != nil {
		return err
	}
	return nil
}

func (s *Stack) CreateStack() (resourcemanager.CreateStackResponse, error) {

	resq := resourcemanager.CreateStackRequest{
		CreateStackDetails: resourcemanager.CreateStackDetails{
			CompartmentId: &s.CompartmentID,
			DisplayName:   &s.Name,
			Description:   common.String("okectl generated stack for cluster"),
			ConfigSource: resourcemanager.CreateZipUploadConfigSourceDetails{
				ZipFileBase64Encoded: common.String(s.Zipfile),
			},
			TerraformVersion: common.String(tf_version),
		},
	}

	resp, err := s.Client.CreateStack(context.Background(), resq)
	if err != nil {
		return resourcemanager.CreateStackResponse{}, err
	}
	return resp, nil
}
